source 'https://rubygems.org'
gem 'sinatra',         '1.4.5'
gem 'sinatra-contrib', '1.4.2'
gem 'unicorn',         '4.8.3'
gem 'json',            '1.8.1'
gem 'mysql2',          '0.3.13'
gem 'mysql2-cs-bind',  '0.0.6'
gem 'uuid',            '2.3.7'
gem 'rubyzip'
gem "debugger"
